.eslintrc.js, README.md, src/components/RawDataViewer.vue
Hi 👋 . They're very minor ones, but I just noticed them while playing with the application 🙇 
`Instrucions` to `Instructions`
```
$ npm run lint
/xxx/copilot-metrics-viewer/src/api/GitHubApi.ts
23:48  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
/xxx/copilot-metrics-viewer/src/components/MetricsViewer.vue
85:71  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
88:86  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
91:57  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
94:73  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
/xxx/copilot-metrics-viewer/src/components/RawDataViewer.vue
32:29  warning …
```
=> Fix for lint errors and a typo

src/components/MetricsViewer.vue
This pull request introduces a new feature to the `MetricsViewer` component in the `src/components/MetricsViewer.vue` file. The changes include the addition of a new tiles section to display various metrics, and modifications to the data processing logic to calculate cumulative metrics and acceptance rate average. 
Here are the most important changes:
UI Enhancements:
* [`src/components/MetricsViewer.vue`](diffhunk://#diff-3232f8c11e48e57eba48531f39e477604432e91bafd81119783d472a38ad3f10R8-R35): Added a new tile-based layout for displaying metrics. Each tile represents a different metric.
* [`src/components/MetricsViewer.vue`](diffhunk://#diff-3232f8c11e48e57eba48531f39e477604432e91bafd81119783d472a38ad3f10R340-R355): Added CSS styles for the new tiles.
Data Calculation and Display:
* …
=> Metrics tiles

src/components/CopilotChatViewer.vue, src/components/MetricsViewer.vue, src/model/MetricsData.ts
This pull request primarily includes changes to enhance the `CopilotChatViewer.vue` component and the `MetricsData.ts` model in the `src` directory. The most important changes are the addition of new elements and data visualizations to the `CopilotChatViewer.vue` component, and the extension of the `MetricsData.ts` model to support new metrics related to chat interactions.
User Interface Enhancements:
* [`src/components/CopilotChatViewer.vue`](diffhunk://#diff-7507fa0fc82a3addc43396ea8f10b51bc91d7fcc588f1f0c665be36ec06cd787R2-R189): Added an API error message to improve user experience when an error occurs.
* [`src/components/CopilotChatViewer.vue`](diffhunk://#diff-7507fa0fc82a3addc43396ea8f10b51bc91d7fcc588f1f0c665be36ec06cd787R2-R189): Introduced two new cards to display the cumulative …
=> Adds Copilot Chat Metrics support

src/assets/copilot_metrics_response_sample.json, src/components/LanguagesBreakdown.vue
This pull request includes changes to the `src/assets/copilot_metrics_response_sample.json` and `src/components/LanguagesBreakdown.vue` files. The changes in the `copilot_metrics_response_sample.json` file add new metrics related to chat interactions, while the changes in the `LanguagesBreakdown.vue` file modify the way language data is presented and sorted.
Changes to `src/assets/copilot_metrics_response_sample.json`:
* Added chat metrics, including `total_chat_acceptances`, `total_chat_turns`, and `total_active_chat_users`, to multiple sections of the JSON data structure. This will provide more detailed metrics about chat usage. 
Changes to `src/components/LanguagesBreakdown.vue`:
* Added a new pie chart to display the top 5 languages by acceptance rate. …
=> Add Pie chart of top 5 languages by acceptance rate

CONTRIBUTING.md, README.md
This updates the organization name from `github-copilot-community` to `github-copilot-resources`
=> Update organization name

src/api/GitHubApi.ts, src/components/MainComponent.vue
This pull request primarily focuses on improving the handling of environment variables in the `GitHubApi.ts` and `MainComponent.vue` files. The changes include adding a console log to notify when mock data is being used, throwing an error when the `VUE_APP_GITHUB_TOKEN` environment variable is not set, and displaying a message on the main component when mock data is being used.
User Feedback Enhancements:
* [`src/api/GitHubApi.ts`](diffhunk://#diff-ff4596c402e6efadb43c85060ff584bf5a5e60010f5efd0b1f702dcc1cc413a5L20-R20): Added a console log to inform the developer when the application is using mock data.
* [`src/components/MainComponent.vue`](diffhunk://#diff-e9eea4ec690e7649e2f812dfa7620e6200d892450dceb379d53e72f9be2894afL9-R9): Added a dynamic error message to the main component's UI to …
=> Add error handling for missing GitHub token and explicitly stating VUE_APP_MOCKED_DATA=true in the UI

src/components/MetricsViewer.vue
This pull request primarily focuses on refactoring the calculation of the `acceptanceRateAverage` in the `MetricsViewer.vue` file. The calculation is now based on the cumulative number of acceptances and suggestions, rather than the average of daily acceptance rates.
Here are the key changes:
* [`src/components/MetricsViewer.vue`](diffhunk://#diff-3232f8c11e48e57eba48531f39e477604432e91bafd81119783d472a38ad3f10L256-R260): Removed the `sum` variable and its incrementation within the `acceptanceRates` map function. The `acceptanceRateAverage` value is no longer calculated within this function.
* [`src/components/MetricsViewer.vue`](diffhunk://#diff-3232f8c11e48e57eba48531f39e477604432e91bafd81119783d472a38ad3f10R276-R281): Added a conditional to check if `cumulativeNumberSuggestions` is …
=> Refactor acceptance rate calculation in MetricsViewer.vue

package-lock.json, package.json
This pull request includes a minor update to the `package.json` file. The version of the `copilot-metrics-viewer` package has been incremented from `1.4.0` to `1.5.0`.
=> chore: Bump version to 1.5.0 in package.json and package-lock.json

src/assets/global.css, src/components/BreakdownComponent.vue, src/components/CopilotChatViewer.vue, src/components/MetricsViewer.vue, src/components/SeatsAnalysisViewer.vue, src/main.ts
This pull request primarily focuses on refactoring the CSS styles and HTML structure of various Vue components in the project. The changes are mainly centered around the extraction of common styles to a global CSS file and the adjustment of HTML structure and class assignments to better use these styles. 
CSS Centralization:
* [`src/assets/global.css`](diffhunk://#diff-1e9fff90a9d1e35b814277ccfa7070ec4425260507a23df53777351ab3e57e2bR1-R14): Added new CSS classes `.tiles-container`, `.tiles-text`, and `.error-message` for common styling across different components.
* [`src/main.ts`](diffhunk://#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR5): Imported the `global.css` file to make the CSS classes available globally across the application.
CSS Removal:
* …
=> formatting changes

package-lock.json, package.json
This pull request includes a minor version update in the `package.json` file for the `copilot-metrics-viewer` project. The version has been updated from `1.5.0` to `1.6.0`.
=> chore: Bump version to 1.6.0 in package.json and package-lock.json

.env, README.md
This pull request includes changes to the `.env` file and the `README.md` file. The changes primarily involve the modification of the scopes required for the GitHub Personal Access Token used for API calls.
=> chore: Update GitHub Personal Access Token scopes in .env and README

Dockerfile
Bumping the production-stage container image from `nginx:1.19` to `nginx:1.26` should eliminate more than 200 vulnerability findings - including 34 CVEs rated at critical (as of 11-Jul-2024).
**Prisma Twistlock Summary using `nginx1.19`**
Vulnerabilities found for image `ghcr.io/github-copilot-resources/copilot-metrics-viewer:latest`:
- total - 201
- critical - 34
- high - 72
- medium - 95
- low - 0
[copilot-metrics-viewer__vulnerability_scan_7_12_24_12_02_41.csv](https://github.com/user-attachments/files/16192796/copilot-metrics-viewer__twistlock_scans_7_12_24_12_02_41.csv)
=> Bump production-stage image to nginx:1.26

.dockerignore, Dockerfile, README.md, docker-entrypoint.d/99-config-app.sh, public/assets/app-config.js, public/index.html, src/api/ExtractSeats.ts, src/api/GitHubApi.ts, src/components/ApiResponse.vue, src/components/MainComponent.vue, src/config.ts
fix: #30
This pull request includes significant changes to the Docker configuration and the way the application handles environment variables. The most important changes are the addition of a `.dockerignore` file, updates to the `Dockerfile`, and the creation of a new `config.ts` file that handles environment variables differently depending on whether the application is in production or development mode. The application's Vue components and API calls have also been updated to use this new configuration file.
=> Externalize config from Docker image

src/components/SeatsAnalysisViewer.vue
Added serial number in the **Seat Analysis** tab, see screen shot below
This is useful when the number of seats are 100+
_Not a **js** programmer, used GH copilot :)_
=> add serial number in the seat analysis tab

src/components/SeatsAnalysisViewer.vue
This pull request includes several changes to the `SeatsAnalysisViewer.vue` component to enhance its functionality and improve code readability. The most important changes include updating the display logic for seat analysis, modifying the data structure for seat counts, and refining the component's styling.
* Updated the display logic to show the number of seats with no activity in the last 7 and 30 days, and the number of seats never used. This change involved adding new computed properties and updating the template to reflect these counts. [[1]](diffhunk://#diff-ab0ce56718bd87d55c7b6acfbd15c636826f0bdcd0fa3a836d950a609736f09cL16-R50) [[2]](diffhunk://#diff-ab0ce56718bd87d55c7b6acfbd15c636826f0bdcd0fa3a836d950a609736f09cL118-R164) …
=> Seats not active in 30 days

nuxt.config.ts, server/routes/auth/github.get.ts
When `NUXT_PUBLIC_IS_PUBLIC_APP` is set to true, application will read GitHub app installations for logged in user and redirect to the first organization on the returned list.
=> support for public gh app

app/components/MainComponent.vue, server/routes/auth/github.get.ts
Supporting custom scopes for GitHub
=> Fix #142 GitHub custom scopes

app/components/SeatsAnalysisViewer.vue
The "no show seats" are showing wrong numbers in case of the 'last_activity_at' property not present in the api response. This fixes the stats making the real "no show seats" visible.
=> fix no show seats

package.json, server/modules/authentication.ts
Closes #184 and #190.
Throw an error if a token does not exist when building the Authorization header.
When using the GitHub OAuth app to authenticate, this is the `secure` object:
```
secure {
tokens: {
access_token: 'ghu_xxxxxxxxxxxxxxxxxxx',
token_type: 'bearer',
scope: ''
},
expires_at: null
}
```
`expires_at` is null, so it always calls `buildHeaders` with an empty string (which doesn't make sense).
Removed this erroneous code and throw an error if the header is being built without a token.
=> Fix Authentication token expiration check

.github/workflows/playwright.yml, .gitignore, Dockerfile, app/components/MainComponent.vue, e2e-tests/copilot.ent.spec.ts, e2e-tests/copilot.org.spec.ts, e2e-tests/copilot.team.spec.ts, e2e-tests/metrics.spec.ts, package-lock.json, package.json, server/modules/authentication.ts
This pull request introduces several changes aimed at improving test configurations, enhancing error handling, and updating dependencies. The main updates include adding support for mocked data in tests, refining error messages, and upgrading the Nuxt.js framework version. Below is a categorized summary of the most important changes:
* Updated Playwright test workflows in `.github/workflows/playwright.yml` to include environment variables for mocked data and GitHub organization settings (`NUXT_PUBLIC_IS_DATA_MOCKED` and `NUXT_PUBLIC_GITHUB_ORG`). [[1]](diffhunk://#diff-7afcd2d8f7b49bda74843f209eefb7b2da45f7e7803bf2e4bd636699b76aa2d3L42-R47) [[2]](diffhunk://#diff-7afcd2d8f7b49bda74843f209eefb7b2da45f7e7803bf2e4bd636699b76aa2d3R73-R74)
* Modified e2e test files …
=> nuxt upgrade to 3.17.5

package.json
=> Update package.json for version 2.0.7

server/middleware/github.ts, tests/github-middleware.nuxt.spec.ts
disable auth for healtcheck endpoints - fixes #268
=> fix #268 disable auth for healtcheck endpoints
